node {

    stage 'Checkout'

    git branch: 'master', url: 'https://github.com/raffamendes/examples.git'   

    // Get the maven tool

    // ** NOTE: This 'M3' maven tool must be configured in the global configuration

    def mvnHome = tool 'M3'

    

    stage 'Build'

    sh "${mvnHome}/bin/mvn package -Pnative -Dquarkus.native.container-build=true -DskipTests -f register-api/pom.xml"

}
